### ISSUE TITLE
[Feature Request] Add blocked words/ability to disable 3rd party emotes (selective)

### ISSUE THREAD

**Issue by DarrenWarrenV** [crackededed/Xtra#257] opened 2023-04-17 08:02 UTC
Hi! Could you add the option to block some words or emotes (selective)? It's mainly about 7TV, some emotes there have RIDICULOUS size and while I'm watching streams at 360p and I'm at 200-300K/s, it can jump up to 2.7M/s for a long time when people spam some emotes from there. Not everyone has unlimited data plans and perfect reception. This is so essential, if you could please add it? Thank you.

**Comment by H2P-iBdg** [comment] 2024-04-04 12:32
Duplicate of #213

**Closed** 2024-04-06 13:21 UTC
