### ISSUE TITLE
Xtra closes down or crashes after a while

### ISSUE THREAD

**Issue by Garries420** [crackededed/Xtra#445] opened 2024-03-05 08:07 UTC
Xtra has worked as it should for days, even since last update, but today it just decides to crash/close down without any message. Happen 4 times already, i even tried restarting the phone in hopes it would work, but it didnt.
Theres no specific timer on when the crashes happen, but its minimum 3-4min in

**Comment by crackededed** [comment] 2024-03-05 10:58
what app version?

**Comment by Garries420** [comment] 2024-03-05 11:08
2.29.1

**Comment by crackededed** [comment] 2024-03-05 13:23
it's fixed on newer versions. the crash is caused by channel point messages without user input. you could turn off Enable PubSub in settings to hide them for now

**Closed by crackededed** 2024-03-05 13:23 UTC
