### ISSUE TITLE
[Feature request]: backup & restore feature

### ISSUE THREAD

**Issue by tuxayo** [crackededed/Xtra#207] opened 2022-12-23 16:30 UTC
To be able to move as much as possible stuff between phones

**Comment by nightznero** [comment] 2023-01-28 23:54
Agree,Would be nice. Bumping thread

**Comment by LukasThyWalls** [comment] 2023-05-13 18:12
Every time i need to test something with a new version not included yet in F-Droid (#285 the last one), i need to copy the bookmarks somehow to recover them before, losing also the video positions and the settings.

Also if you want to use the app in local mode, you can keep the local followed channels.

So, i could be a nice feature at least for keeping some data from the app.

Thanks!

**Comment by H2P-iBdg** [comment] 2024-04-04 12:46
Duplicate of #72

**Comment by crackededed** [comment] 2024-09-19 20:33
added

**Closed by crackededed** 2024-09-19 20:33 UTC
