### ISSUE TITLE
[Feature Request] Material You (3.0) design

### ISSUE THREAD

**Issue by KakarottoCake** [crackededed/Xtra#112] opened 2022-07-18 10:18 UTC
Material You will allow the app to use colors that are synonymous with the system's color scheme, and in addition makes buttons and icons more modern and responsive. This isn't a necessity but it's always nice to have to one-up the official client (which doesn't have Material You)

**Comment by crackededed** [comment] 2022-07-29 21:53
i'll probably take a look at this at some point. closing this as duplicate of #77

**Closed by crackededed** 2022-07-29 21:53 UTC
